### ISSUE TITLE
Add representatives of each ALC to lcwg team

### ISSUE THREAD

**Issue by hbogner** [osmfoundation/lcwg#2]
osmfoundation github organization uses teams structure for access to each repo, add at least one representative to the team from active local chapters: https://wiki.openstreetmap.org/wiki/Foundation/Local_Chapters

- [x] France
- [ ] Germany
- [ ] Iceland
- [ ] Italy
- [ ] Switzerland
- [x] United Kingdom
- [x] Belgium

**Comment by althio** [comment]
I can participate as one member from France.

**Comment by RobJN** [comment]
Add me for the UK please.

**Comment by jnicho02** [comment]
Me for UK please

**Comment by hbogner** [comment]
There are some limitation on what I can do, and who I can add. I forwarded the request to more privileged maintainers of this organization.

**Comment by Zverik** [comment]
Added @jnicho02 and @sabas. Thanks for offering your support guys!

**Comment by joostschouppe** [comment]
Closing because we moved to https://gitlab.com/osmfoundation/lccwg/
