### ISSUE TITLE
Document (A)LC

### ISSUE THREAD

**Issue by sabas** [osmfoundation/lcwg#3]
What should be documented by each local chapter?
- [ ] Contact information
- [ ] Useful documentation on the organization (legal?)
- [ ] Hardware resources
- [ ] Software in use for / software developed in the scope of the group activities
- [ ] ...

How? As documents in this repo or wiki.

**Comment by hbogner** [comment]
After the documentation is somehow sorted I can edit https://wiki.osmfoundation.org/wiki/Local_Chapters_Working_Group to represent newest data.

**Comment by RobJN** [comment]
- Size (approx number of members)
- How membership sign up is done.
- Membership fee
- Are corporate members allowed
- Aims/mission statement

We could also do with a project map - listing a high level the projects that each LC has done / is working on.

**Comment by xivk** [comment]
We have 2 goals here I think, first to make a list of who is a local chapter and keep the details up-to-date but what we're collecting here may be more about sharing experiences. 

Perhaps this repo is better for the details and experience sharing? I would suggest one markdown file per chapter with a description and some more details and this list: https://wiki.openstreetmap.org/wiki/Foundation/Local_Chapters#Active_local_chapters as a general overview?

**Comment by joostschouppe** [comment]
Closing this here, but feel free to re-open at https://gitlab.com/osmfoundation/lccwg/
